
# name: CI-CD Cloud Run

# on:
#   push:
#     branches: ["main"]

# jobs:
#   build-deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v4

#       - uses: actions/setup-java@v4
#         with:
#           distribution: temurin
#           java-version: 17

#       - name: Build using Maven
#         run: mvn -B package --file pom.xml

#       - name: Authenticate GCP
#         uses: google-github-actions/auth@v2
#         with:
#           credentials_json: "${{ secrets.GCP_SA_KEY }}"

#       - name: Set up Cloud SDK
#         uses: google-github-actions/setup-gcloud@v2

#       - name: Configure Docker
#         run: gcloud auth configure-docker gcr.io --quiet

#       - name: Build & Push Docker Image
#         run: |
#           IMAGE=gcr.io/${{ secrets.GCP_PROJECT_ID }}/springboot-cloudrun
#           docker build -t $IMAGE .
#           docker push $IMAGE

#       - name: Deploy to Cloud Run
#         run: |
#           gcloud run deploy springboot-cloudrun             --image=gcr.io/${{ secrets.GCP_PROJECT_ID }}/springboot-cloudrun             --region=us-central1             --platform=managed             --allow-unauthenticated



name: Dev Pipeline

on:
  push:
    branches-ignore:
      - main
      - test

jobs:
  dev:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - uses: actions/checkout@v4

      - name: Dev step
        run: |
          echo "Branch: ${{ REGION }}"
          echo "Running DEV pipeline"
